import { ArrowDown, ArrowRight, Fingerprint, Orbit, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ScannerHUD } from './ui/scanner-hud';

export default function LandingPage() {
  return <div className="veylora-hero">
    <div className="veylora-orb" />
    <section className="relative z-10 mx-auto grid min-h-[calc(100vh-72px)] max-w-7xl grid-cols-12 items-stretch px-5 lg:px-8">
      <div className="col-span-12 flex flex-col justify-between py-12 md:col-span-3 md:py-20"><div><p className="veylora-kicker">Cipher intelligence</p><p className="mt-8 max-w-[12rem] text-sm leading-6 text-white/75"><span className="text-3xl font-bold text-white">W</span>here the signal becomes visible, and encrypted data reveals its story.</p></div><div className="hidden gap-5 text-xs font-semibold text-white/65 md:flex"><span>ANALYZE</span><span>PROTECT</span><span>UNDERSTAND</span></div></div>
      <div className="col-span-12 flex flex-col items-center justify-center py-12 text-center md:col-span-6"><p className="veylora-kicker mb-9">Machine learning · cryptography</p><h1 className="veylora-title relative z-10">VEY<span className="veylora-outline">LORA</span></h1><div className="mt-14 flex flex-col items-center gap-5"><Link to="/signup" className="veylora-ring">ENTER<br/>STUDIO</Link><p className="max-w-xs text-sm leading-6 text-white/70">Decode cryptographic patterns with a more intuitive intelligence layer.</p></div></div>
      <div className="col-span-12 flex flex-col justify-between py-12 text-left md:col-span-3 md:py-20 md:text-right"><Link to="/signup" className="ml-0 inline-flex items-center gap-2 self-start rounded-full border border-white/40 bg-white/10 px-4 py-2 text-xs font-bold text-white backdrop-blur-md md:ml-auto md:self-auto">Access workspace <ArrowRight size={14}/></Link><div><p className="text-sm font-semibold text-white">Scroll to explore</p><ArrowDown className="mt-2 inline-block text-fuchsia-200" size={20}/></div></div>
    </section>
    <section className="relative z-10 mx-auto grid max-w-7xl grid-cols-12 border-t border-white/15 px-5 lg:px-8"><div className="veylora-column col-span-12 py-10 md:col-span-3"><p className="text-4xl font-light leading-none tracking-tight text-white">What is<br/><strong>Veylora?</strong></p></div><div className="veylora-column col-span-12 py-10 md:col-span-5"><p className="max-w-sm text-xl leading-8 text-white">We make cryptographic analysis feel less opaque—combining machine learning, data signals, and a little curiosity.</p></div><div className="veylora-column col-span-12 py-10 md:col-span-4"><p className="text-3xl font-light leading-none text-white">Be part of<br/>the <strong>new cipher<br/>language.</strong></p><Link to="/prediction" className="mt-6 inline-flex items-center gap-2 rounded-full border border-white/70 px-4 py-2 text-xs font-bold text-white hover:bg-white hover:text-[#1a0a19]">Run detection <Fingerprint size={15}/></Link></div></section>
    <section className="relative z-10 mx-auto grid max-w-7xl grid-cols-12 border-t border-white/15 px-5 py-12 lg:px-8 lg:py-20"><div className="col-span-12 md:col-span-7"><p className="max-w-lg text-4xl font-light leading-[.94] tracking-tight text-white sm:text-6xl">WE DON'T JUST<br/><strong>CLASSIFY CIPHERS.</strong><br/>WE CREATE CLARITY.</p><p className="mt-8 max-w-md text-sm leading-7 text-white/65">Bring any hexadecimal payload into the Veylora workspace. Our model surfaces the strongest match, confidence rankings, and the evidence behind every result.</p><Link to="/prediction" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-fuchsia-200 hover:text-white">Open the detector <ArrowRight size={17}/></Link></div><div className="veylora-card col-span-12 mt-10 grid min-h-72 place-items-center overflow-hidden md:col-span-5 md:mt-0"><ScannerHUD><div className="relative grid place-items-center"><div className="veylora-spin-target relative grid h-44 w-44 place-items-center rounded-full border border-fuchsia-200/40 bg-fuchsia-500/10 transform-gpu [will-change:transform]"><Orbit className="absolute h-36 w-36 text-fuchsia-300/50" strokeWidth={.8}/><ShieldCheck className="h-12 w-12 text-fuchsia-100"/></div><span className="absolute -bottom-6 text-[10px] font-mono tracking-[.28em] text-white/70">PATTERN FOUND</span></div></ScannerHUD></div></section>
    <section className="relative z-10 border-t border-white/15 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="veylora-kicker">Built for the invisible</p><h2 className="mt-5 max-w-3xl text-4xl font-light leading-tight tracking-tight text-white sm:text-6xl"><strong>Cryptography</strong> deserves an interface as intelligent as the systems it protects.</h2><div className="mt-10 flex flex-wrap gap-3"><Link to="/docs" className="rounded-full bg-white px-5 py-3 text-sm font-bold text-[#1d0b1e] hover:bg-fuchsia-100">Explore algorithms</Link><Link to="/encry" className="rounded-full border border-white/45 px-5 py-3 text-sm font-bold text-white hover:bg-white/10">Encrypt data</Link></div><div className="mt-14 flex items-center gap-3 text-sm text-white/65"><Sparkles size={16} className="text-fuchsia-300"/>15 algorithms · instant pattern detection · secure workspace</div></div></section>
  </div>;
}
